version: 2
jobs:
  build:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: make install

      - run:
          name: Test notebooks
          command: |
            cd notebooks
            make test
      
      - run:
          name: Check for dependabot branch  # continue only if last commit belongs to dependabot
          command: if [ `git log -1 --pretty=format:'%cn'` != "dependabot[bot]" ] ; then circleci step halt ; fi

      - run:
          name: Commit notebooks updated by tests
          command: |
            git config user.email "contact@openfisca.fr"
            git config user.name "openfisca-bot" 
            git add .
            git commit -m "Save notebooks execution results"
            git push --set-upstream origin `git name-rev --name-only HEAD`

workflows:
  version: 2
  build:
    jobs:
      - build
