version: 2
jobs:
  build:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: make install

      - run:
          name: Test notebooks
          command: |
            cd notebooks
            make test

workflows:
  version: 2
  build:
    jobs:
      - build
